### ISSUE TITLE
Crashing after 10 seconds on Google Pixel 8a with Android 15

### ISSUE THREAD

**Issue by 88572** [juandjara/wafrn-rn#5]
To reproduce:
- Launch app
- Wait ~10 seconds and scroll

Logs:
```
FATAL EXCEPTION: main
Process: dev.djara.wafrn_rn, PID: 28626
java.lang.OutOfMemoryError: Failed to allocate a 24 byte allocation with 237360 free bytes and 231KB until OOM, target footprint 268435456, growth limit 268435456; giving up on allocation because <1% of heap free after GC.
	at android.graphics.Insets.of(Insets.java:64)
	at android.graphics.Insets.max(Insets.java:117)
	at android.view.WindowInsets.getInsets(WindowInsets.java:239)
	at android.view.WindowInsets.getInsets(WindowInsets.java:362)
	at com.horcrux.svg.TSpanView$$ExternalSyntheticApiModelOutline0.m(Unknown Source:0)
	at com.th3rdwave.safeareacontext.SafeAreaUtilsKt.getRootWindowInsetsCompatR(SafeAreaUtils.kt:15)
	at com.th3rdwave.safeareacontext.SafeAreaUtilsKt.getRootWindowInsetsCompat(SafeAreaUtils.kt:55)
	at com.th3rdwave.safeareacontext.SafeAreaUtilsKt.getSafeAreaInsets(SafeAreaUtils.kt:67)
	at com.th3rdwave.safeareacontext.SafeAreaProvider.maybeUpdateInsets(SafeAreaProvider.kt:18)
	at com.th3rdwave.safeareacontext.SafeAreaProvider.onPreDraw(SafeAreaProvider.kt:39)
	at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:1176)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:4239)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2917)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:10324)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1406)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1415)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1015)
	at android.view.Choreographer.doFrame(Choreographer.java:945)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1389)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8705)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:886)
```

**Comment by juandjara** [comment]
@everypizza1 any idea on what could be causing the Out of Memory Error? Cause I'm running on a device that is at least half as powerful as a Pixel 8a and had no problem like this so far

I'm going to check people you follow to see if I can replicate the problem

**Comment by 88572** [comment]
Oh, it looks like I had too much stuff running in the background. I pressed the Clear All button on the recents screen, and now the app works fine.
